enyo.depends(
  "$lib/layout",
  "$lib/onyx",
  "$lib/canvas-spinner",
  "$lib/more-arrangers",
  "$lib/geolocation",
  "$lib/maps",
  "Main.css",
  "Main.js",
  "SpaceInfo.js",
  "Spaces.js",
  "Scroller.js"
);
